Moved configuration file to $XDG_CONFIG_HOME.  wi checks the config to see if color should be used in output messages now

diff --git a/wi b/wi
--- a/wi
+++ b/wi
@@ -20,16 +20,17 @@
 #-----------
 # Variables
 #-----------
-version='0.0.6-indev'
-wi_home="/etc/wi"
+version='0.0.7-indev'
+wi_home="$XDG_CONFIG_HOME/wi"
 wi_conf="$wi_home/wi.conf"
 iface=''
 essid=''
 enc=''
 color=''
-green='\e[0;32m'
-red='\e[0;31m'
-yellow='\e[0;93m'
+green=''
+red=''
+yellow=''
+reset=''
 
 #------------
 # Exit codes
@@ -52,19 +53,26 @@ iwlist_scan_failed='100' # scanning with iwlist failed
 # Usage
 #-----------
 function echo_usage {
-  echo "Usage: wi [arguments]" 
-  echo "  -o, --open interface essid      Connect to an open or unsecured wireless"
-  echo "                                  network via dhcp"
-  echo "  -e, --wep interface essid pass  Connect to a WEP secured network using the"
-  echo "                                  password 'pass'"
-  echo "  -a, --wpa interface essid pass  Connect to a WPA secured network using the"
-  echo "                                  password 'pass' "
-  echo "  -w, --wired interface           Connect to a wired network using interface"
-  echo "                                  via dhcp "
-  echo "  -t, --test                      Check for a current internet connection"
-  echo "  -s, --scan interface            Scan for wireless networks with interface"
-  echo "  -h, --help                      Show this menu"
-  echo "  --version                       Print the current version of wi"
+  echo -e "Usage: wi [arguments]" 
+  echo -e "  -o, --open interface essid      Connect to an open or unsecured wireless"
+  echo -e "                                  network via dhcp"
+  echo -e "  -e, --wep interface essid pass  Connect to a WEP secured network using the"
+  echo -e "                                  password 'pass'"
+  echo -e "  -a, --wpa interface essid pass  Connect to a WPA secured network using the"
+  echo -e "                                  password 'pass' "
+  echo -e "  -w, --wired interface           Connect to a wired network using interface"
+  echo -e "                                  via dhcp "
+  echo -e "  -t, --test                      Check for a current internet connection"
+  echo -e "  -s, --scan interface            Scan for wireless networks with interface"
+  echo -e "  -h, --help                      Show this menu"
+  echo -e "  --version                       Print the current version of wi"
+}
+
+function init_color {
+  green='\e[0;32m'
+  red='\e[0;31m'
+  yellow='\e[0;93m'
+  reset='\e[0m'  
 }
 
 #-----------------
@@ -107,7 +115,7 @@ parse_arguments() {
 }
 
 exit_noargs() {
-  echo "Missing argument for $1 (See wi -h,--help)" && exit $missing_arguments
+  echo -e "$yellow[Missing argument for $1 (See wi -h,--help)]$reset" && exit $missing_arguments
 }
 
 assign_arguments() {
@@ -155,11 +163,12 @@ ping_check() {
 # Test
 #------
 test_connection() {
+  check_config
   ping_check
-  if [[ $? -ne 0 ]];then
-    echo "[Connected]"
+  if [[ $? -eq 0 ]];then
+    echo -e "$green[Connected]$reset"
   else
-    echo "[No connection]"
+    echo -e "$yellow[No connection]$reset"
   fi
 }
 
@@ -170,7 +179,7 @@ scan() {
   assign_arguments $*
   ensure_root && check_exit $not_root
   isUp
-  echo "[Scanning for networks with $iface]"
+  echo -e "$green[Scanning for networks with $iface]$reset"
   iwlist $iface scan | grep ESSID | tr -d [:blank:] | tr -d [\"] #TODO this is totally fucked up
   # this needs to iterate through them one by one and avoid printing empty strings
   # it needs to print out encryption details, and probably some other important data.
@@ -180,9 +189,9 @@ scan() {
 
 check_scan() {
   if [[ $? -ne 0 ]];then
-    echo "[Scan complete]" && exit 0
+    echo -e "$green[Scan complete]$reset" && exit 0
   fi
-  echo "[Scan failed]" && exit $iwlist_scan_failed 
+  echo -e "$red[Scan failed]$reset" && exit $iwlist_scan_failed 
 }
 
 #--------------------
@@ -190,17 +199,21 @@ check_scan() {
 #--------------------
 check_config() {
   if [[ -r $wi_conf ]]; then
-    . $wi_conf && return
+    . $wi_conf
+    [[ $color == true ]] && init_color
+    return
   fi 
-  echo "[Created new configuration file at $wi_conf]"
   mkdir -p $wi_home && touch $wi_conf
   write_default_config
+  echo -e "$green[Created new configuration file at $wi_conf]$reset"
 }
 
 write_default_config() {
-  write "# wi configuration file"
+  write "#"
+  write "# wi.conf - wi configuration file"
+  write "#"
   write ""
-  write "# use color? true/false"
+  write "# use color in terminal messages? true/false"
   write "color=false"
 }
 
@@ -213,7 +226,7 @@ write() {
 #------------------
 ensure_root() {
   if [[ $EUID -ne 0 ]];then
-    echo "You must be root to manage network interfaces" && exit $not_root
+    echo -e "$yellow[You must be root to manage network interfaces]$reset" && exit $not_root
   fi
 }
 
@@ -223,14 +236,14 @@ validate_essid() {
     do
       [[ "ESSID:$essid" == "$scanned_essid" ]] && return
     done
-  echo -e "$red[Network \"${yellow}$essid${red}\" not found]$reset"
+  echo -e "$yellow[Network \"${yellow}$essid${red}\" not found]$reset"
   exit $network_not_found
 }
 
 validate_interface() {
   ip link show dev $iface &>/dev/null
   [[ $? -eq 0 ]] && return
-  echo -e "$red[Network interface \"${yellow}$iface$red\" not detected]$reset"
+  echo -e "$yellow[Network interface \"${yellow}$iface$red\" not detected]$reset"
   exit $interface_not_found
 }
 
@@ -248,7 +261,7 @@ check_connectioni() {
 
 check_exit() {
   if [[ $? -ne 0 ]];then
-    echo "[Error] exit: $1" && exit $1
+    echo -e "$red[Error] exit: $1$reset" && exit $1
   fi
 }
 
@@ -259,8 +272,8 @@ dhcp_persist() {
   let j=1
   while (( j -lt 5 )) && (( $? -gt 0 ))
     do
-    echo "[Failed to lease an IP]"
-    echo "[Retrying ($j/5)]"
+    echo -e "$yellow[Failed to lease an IP]$reset"
+    echo -e "$yellow[Retrying ($j/5)]$reset"
     retry_wireless_dhcp
     ((j+=1))
    done 
@@ -293,10 +306,10 @@ retry_if_needed() {
 generic_wireless() {
   pre_connect
   validate_interface
-  echo "[Scanning]" && validate_essid
-  echo "[Resetting environment]" && reset_environment
+  echo -e "$green[Scanning]$reset" && validate_essid
+  echo -e "$green[Resetting environment]$reset" && reset_environment
   sleep 1
-  echo "[Associating with $essid]" && associate
+  echo -e "$green[Associating with $essid]$reset" && associate
   sleep 1
 }
 
@@ -306,10 +319,11 @@ generic_wireless() {
 connect_unsecured_wireless_dhcp() {
   assign_arguments $*
   generic_wireless
-  echo "[Putting $iface up]" && put_interface_up
+  echo -e "$green[Putting $iface up]$reset" && put_interface_up
   sleep 1
-  echo "[Starting dhcp]" && start_dhcpcd
-  check_connection && retry_if_needed
+  echo -e "$green[Starting dhcp]$reset" && start_dhcpcd
+  check_connection
+  retry_if_needed
 }
 
 retry_wireless_dhcp() {
@@ -330,11 +344,11 @@ retry_wireless_dhcp() {
 connect_wireless_WEP_dhcp() {
   assign_arguments $* 
   generic_wireless
-  echo "[Setting WEP encyption]" && set_wep_encryption
+  echo -e "$green[Setting WEP encyption]$reset" && set_wep_encryption
   sleep 1
-  echo "[Putting $iface up]" && put_interface_up
+  echo -e "$green[Putting $iface up]$reset" && put_interface_up
   sleep 1
-  echo "$green[Acquiring an IP address]$reset" && start_dhcpcd
+  echo -e "$green[Acquiring an IP address]$reset" && start_dhcpcd
   test_connection
 }
 
@@ -384,11 +398,11 @@ connect_wired_dhcp() {
   assign_arguments $*
   pre_connect
   validate_interface
-  echo "[Resetting environment]" && reset_environment
+  echo -e "$green[Resetting environment]$reset" && reset_environment
   sleep 1
-  echo "[Putting $iface up]" && put_interface_up
+  echo -e "$green[Putting $iface up]$reset" && put_interface_up
   sleep 1
-  echo "[Acquiring an IP address]" && start_dhcpcd
+  echo -e "$green[Acquiring an IP address]$reset" && start_dhcpcd
   sleep 1
   test_connection
 }
